### ISSUE TITLE
Ajuste no layout da tela de login

### ISSUE THREAD

**Issue by adorilson** [fabiano-araujo/ifprof#1]
Centralizar o conteúdo da tela de login. O campos de acesso bem em cima, e o botão de Entrar lá em baixo, junto com o "Não tem conta" ficou pouco intuitivo. Principalmente pra quem vai fazer o primeiro acesso. Veja isso em um tablet, em um celular o problema nao deve ser tão grande e perceptível.

**Comment by adorilson** [comment]
Fechou, mas corrigiu (qual commit?) ou não vai e porque?

**Comment by fabiano-araujo** [comment]
acho q corrigi. o ultimo commit.
